In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr

In [ ]:
data_1 = pd.read_csv('/content/drive/MyDrive/MIT805_Exam/WHO_HealthData.csv')
data_2 = pd.read_csv('/content/drive/MyDrive/MIT805_Exam/WHO_HealthData_Meta.csv')

<ipython-input-3-a9550109b687>:1: DtypeWarning: Columns (3,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  data_1 = pd.read_csv('/content/drive/MyDrive/MIT805_Exam/WHO_HealthData.csv')

In [ ]:
# Rename and merge metadata and data
data_2.rename(columns={'Label': 'GHO'}, inplace=True)
merged_data = data_1.merge(data_2, on='GHO', how='inner')

In [ ]:
# Remove columns with 'Unnamed' in their names
merged_data = merged_data.loc[:, ~merged_data.columns.str.contains('^Unnamed')]

In [ ]:
# Corrected code with parentheses around each condition
filtered_data = merged_data[(merged_data['COUNTRY'] == 'ZAF') | (merged_data['REGION'] == 'GLOBAL')]

In [ ]:
# List of specific values to filter
values_to_select = [
    "WHOSIS_000001", "WHOSIS_000002", "HIV_0000000026", "MDG_0000000020",
    "MALARIA_EST_INCIDENCE", "NCDMORT3070", "RS_196", "SDGSUICIDE",
    "NCD_HYP_PREVALENCE_A", "NCD_BMI_30A", "HWF_0002", "HWF_0003", "HWF_0004",
    "HWF_0007", "HWF_0011", "HWF_0015", "HWF_0016", "HWF_0017", "HWF_0018",
    "HWF_0019", "HWF_0020", "HWF_0021", "HWF_0022", "HWF_0023", "HWF_0024"
]

# Filter the dataframe based on these values in the 'GHO' column
filtered_data = filtered_data[filtered_data['GHO'].isin(values_to_select)]

In [ ]:
filtered_data

,GHO,PUBLISHSTATE,YEAR,REGION,COUNTRY,Display Value,Numeric,Low,High,StdErr,StdDev,Comments,attribute,value,Display_Text
98761,MDG_0000000020,PUBLISHED,2021,GLOBAL,NaN,131 [122-140],131.0,122.0,140.0,NaN,NaN,NaN,WORLDBANKINCOMEGROUP,NaN,Incidence of tuberculosis (per 100 000 populat...
98783,MDG_0000000020,PUBLISHED,2008,GLOBAL,NaN,170 [131-213],170.0,131.0,213.0,NaN,NaN,NaN,WORLDBANKINCOMEGROUP,NaN,Incidence of tuberculosis (per 100 000 populat...
98785,MDG_0000000020,PUBLISHED,2012,GLOBAL,NaN,157 [132-184],157.0,132.0,184.0,NaN,NaN,NaN,WORLDBANKINCOMEGROUP,NaN,Incidence of tuberculosis (per 100 000 populat...
98788,MDG_0000000020,PUBLISHED,2015,GLOBAL,NaN,146 [133-160],146.0,133.0,160.0,NaN,NaN,NaN,WORLDBANKINCOMEGROUP,NaN,Incidence of tuberculosis (per 100 000 populat...
98789,MDG_0000000020,PUBLISHED,2011,GLOBAL,NaN,161 [133-191],161.0,133.0,191.0,NaN,NaN,NaN,WORLDBANKINCOMEGROUP,NaN,Incidence of tuberculosis (per 100 000 populat...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9683153,NCD_HYP_PREVALENCE_A,PUBLISHED,2015,AFR,ZAF,43.8 [39.4-48.2],43.8,39.4,48.2,NaN,NaN,NaN,UNSDGREGION,NaN,Prevalence of hypertension among adults aged 3...
9683154,NCD_HYP_PREVALENCE_A,PUBLISHED,2016,AFR,ZAF,43.8 [38.9-48.7],43.8,38.9,48.7,NaN,NaN,NaN,UNSDGREGION,NaN,Prevalence of hypertension among adults aged 3...
9683155,NCD_HYP_PREVALENCE_A,PUBLISHED,2017,AFR,ZAF,43.8 [38.3-49.5],43.8,38.3,49.5,NaN,NaN,NaN,UNSDGREGION,NaN,Prevalence of hypertension among adults aged 3...
9683156,NCD_HYP_PREVALENCE_A,PUBLISHED,2018,AFR,ZAF,43.8 [37.5-50.3],43.8,37.5,50.3,NaN,NaN,NaN,UNSDGREGION,NaN,Prevalence of hypertension among adults aged 3...
9683157,NCD_HYP_PREVALENCE_A,PUBLISHED,2019,AFR,ZAF,43.8 [36.6-51.2],43.8,36.6,51.2,NaN,NaN,NaN,UNSDGREGION,NaN,Prevalence of hypertension among adults aged 3...

In [ ]:
filtered_data.to_csv('/content/drive/MyDrive/MIT805_Exam/Final_Data/WHO_Data_Analysis.csv')

In [ ]:
merged_data

,GHO,PUBLISHSTATE,YEAR,REGION,COUNTRY,Display Value,Numeric,Low,High,StdErr,StdDev,Comments,attribute,value,Display_Text
0,MDG_0000000001,PUBLISHED,2000,AFR,NaN,90.84 [89.31-92.62],90.83788,89.30656,92.61595,NaN,NaN,NaN,SEX,BTSX,Infant mortality rate (between birth and 11 mo...
1,MDG_0000000001,PUBLISHED,2001,AFR,NaN,87.98 [86.49-89.72],87.97622,86.49111,89.72169,NaN,NaN,NaN,SEX,BTSX,Infant mortality rate (between birth and 11 mo...
2,MDG_0000000001,PUBLISHED,2002,AFR,NaN,85.05 [83.58-86.74],85.04704,83.58373,86.74262,NaN,NaN,NaN,SEX,BTSX,Infant mortality rate (between birth and 11 mo...
3,MDG_0000000001,PUBLISHED,2003,AFR,NaN,82.02 [80.56-83.68],82.01636,80.56035,83.67830,NaN,NaN,NaN,SEX,BTSX,Infant mortality rate (between birth and 11 mo...
4,MDG_0000000001,PUBLISHED,2017,AFR,NaN,54.12 [51.03-58.43],54.11607,51.02641,58.42746,NaN,NaN,NaN,SEX,BTSX,Infant mortality rate (between birth and 11 mo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10917363,R_type_variant,PUBLISHED,2022,WPR,SLB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOBACCO_NICOTINE_PRODUCT,TOBACCO_SMOKELESS_MOSTSOLD,Most sold brand of other tobacco type
10917364,R_type_variant,PUBLISHED,2022,WPR,TON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOBACCO_NICOTINE_PRODUCT,TOBACCO_SMOKELESS_MOSTSOLD,Most sold brand of other tobacco type
10917365,R_type_variant,PUBLISHED,2022,WPR,TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOBACCO_NICOTINE_PRODUCT,TOBACCO_SMOKELESS_MOSTSOLD,Most sold brand of other tobacco type
10917366,R_type_variant,PUBLISHED,2022,WPR,VUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOBACCO_NICOTINE_PRODUCT,TOBACCO_SMOKELESS_MOSTSOLD,Most sold brand of other tobacco type
10917367,R_type_variant,PUBLISHED,2022,WPR,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOBACCO_NICOTINE_PRODUCT,TOBACCO_SMOKELESS_MOSTSOLD,Most sold brand of other tobacco type

Warning: total number of rows (10917368) exceeds max_rows (20000). Limiting to first (20000) rows.
Warning: total number of rows (10917368) exceeds max_rows (20000). Limiting to first (20000) rows.